version: '3.7'
services:
  ci-db:
    container_name: ci-db
    image: mysql:latest
    networks:
      - ci-network
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=kaddemdb
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  ci-app:
    container_name: ci-spring
    image: onstb/onstb:latest
    ports:
      - "8089:8089"
    networks:
      - ci-network
    depends_on:
      - ci-db
    environment:
      - MYSQL_HOST=ci-db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=kaddemdb
      - MYSQL_PORT=3306


networks:
  ci-network:
    name: ci-network

volumes:
  dbvol:
