version: '3'

services:
  db-mysql:
    image: mysql:5.6
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=kaddemdb
    ports:
      - "3307:3306"
    restart: unless-stopped

  kaddem-app:
    image: onstb
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - db-mysql
    environment:
      - MYSQL_HOST=ci-db
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=kaddemdb
      - MYSQL_PORT=3306
