version: '3'

services:
  ci-db:
    container_name: ci-db
    image: mysql:latest
    networks:
      - ci-network
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: kaddemdb
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  ci-app:
    container_name: ci-spring
    image: onstb/onstb:latest
    ports:
      - "8089:8089"
    networks:
      - ci-network
    depends_on:
      - ci-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ci-db:3306/kaddemdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
      LOGGING_LEVEL_ROOT: info
      LOGGING_PATTERN_CONSOLE: '%d{yyyy-MM-dd HH:mm:ss} - %-5level- %logger{45} - %msg %n'
    restart: always

networks:
  ci-network:
    name: ci-network

volumes:
  dbvol:
